title: Egbert Castro # The title of the blog
author: Egbert Castro # Your name 
email: egbert.castro@yale.edu # your email shown in the footer
url: https://www.egbertcastro.com # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  Just a blog about my experience at the interface of biology and machine learning.
favicon: "./favicon.ico" # set the favicon of the site 

google_analytics: UA-102935948-1
show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "assets/about/me.png" # avatar in about page
  about_you: A caffeinated computational biology grad student # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    twitter: egbert_castro
    github:  ec1340
    # rss: RSS
    # # dribbble: 
    # facebook: huangyz0918
    # # flickr:   
    # # instagram: 
    linkedin: castroegbert
    GoogleScholar: igJtvLoAAAAJ
    # # pinterest: 
    # # youtube: 
    # # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
# theme: huangyz0918/moving # note, please use huangyz0918/moving if you want to publish to Github Pages.
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# gem: ['jekyll/scholar']



# scholar:
#   style: apa
#   bibliography: ref.bib
#   replace_strings: true
#   query: "@*"